version: '3'
services:
  express-app:
    build: .
    container_name: express-app
    restart: unless-stopped
    ports:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - npm_network

networks:
  npm_network:
    external: true
